/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpicasst;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Naitsirc98
 */
public class BackgroundColorPanel extends JPanel {
    public BackgroundColorPanel() {
        initComponents();

        Toolkit toolkit = Toolkit.getDefaultToolkit();

    }

    public JComboBox<String> getColorChooser() {
        return colorChooser;
    }

    public JLabel getBackgroundLabel() {
        return backgroundLabel;
    }

    public Color getColor() {
        return Utils.getColor(colorChooser.getSelectedItem().toString());
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundLabel = new javax.swing.JLabel();
        colorChooser = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(120, 70));
        setMinimumSize(new java.awt.Dimension(120, 70));
        setPreferredSize(new java.awt.Dimension(739, 70));

        backgroundLabel.setBackground(new java.awt.Color(0, 0, 0));
        backgroundLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        backgroundLabel.setForeground(new java.awt.Color(255, 255, 255));
        backgroundLabel.setText("BACKGROUND");

        colorChooser.setBackground(new java.awt.Color(255, 255, 255));
        colorChooser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        colorChooser.setForeground(new java.awt.Color(0, 0, 0));
        colorChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "White", "Red", "Green", "Blue", "Yellow", "Orange", "Pink" }));
        colorChooser.setSelectedIndex(1);
        colorChooser.setRenderer(new ColorComboBoxRenderer());
        colorChooser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                colorChooserItemStateChanged(evt);
            }
        });
        colorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backgroundLabel)
                    .addComponent(colorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(backgroundLabel)
                .addGap(4, 4, 4)
                .addComponent(colorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorChooserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_colorChooserItemStateChanged
        // TODO add your handling code here:
        Canvas.getInstance().setBackground(this.getColor());
    }//GEN-LAST:event_colorChooserItemStateChanged

    private void colorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorChooserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JComboBox<String> colorChooser;
    // End of variables declaration//GEN-END:variables

}
